@startuml
actor Diver
actor DiveClub
actor DiveInstructor

left to right direction 

Diver -- (Manage Profile)
Diver -- (Log Dives)
Diver -- (View Dive History)
Diver -- (Manage Equipment)
Diver -- (Certify Dives)

DiveClub -- (Manage Dive Sites)
DiveClub -- (Manage Instructors)
DiveClub -- (View Dive Logs)

DiveInstructor -- (Manage Dives)
DiveInstructor -- (Confirm Dives)

@enduml