@startuml
actor Customer
actor Waiter
actor Chef
actor Admin

left to right direction

Customer -- (Browse Menu)
Customer -- (Select Table)
Customer -- (Order Food)
Customer -- (Pay)
Customer -- (Receive Confirmation)

Waiter -- (View Orders)
Waiter -- (Manage Orders)
Waiter -- (Receive Notifications)

Chef -- (View Orders)
Chef -- (Prepare Food)
Chef -- (Update Order Status)

Admin -- (Configure System)
Admin -- (Manage Users)
Admin -- (Generate Reports)
@enduml