@startuml Smart Ordering System - Use Case Diagram

actor Staff
actor Customer
actor Waiter
actor Chef
actor Admin
left to right direction


Staff -- (View Orders)
Staff -- (Manage Orders)

Waiter -- (Clean Table)

Chef -- (Prepare Food)
Chef -- (Update Order Status)

Admin -- (Configure System)

Waiter -|> Staff
Chef -|> Staff

Customer -- (Browse Menu)
Customer -- (Select Table)
Customer -- (Order Food)
Customer -- (Pay)

@enduml